購入履歴用のhistoryテーブルと、購入明細用のpayment_statementテーブルを作成した #10
ryoma1200/lamp_practice pull request #11
Opened 2020-09-17 07:32 UTC by ryoma1200

購入履歴用のhistoryテーブルと、購入明細用のpayment_statementテーブルを作成しました。
ご確認のほどよろしくお願いいたします。 #10

2020-09-18 13:29 UTC, kamezaki01 requested changes
append_schema.sqlをphpMyAdminからインポートするとエラーが発生します。
エラーがでないようにしましょう。

また、追加した２つのテーブルは冗長的です。
「購入履歴画面」用のテーブルと「購入明細画面」用のテーブルを用意するのではなく、
「購入履歴画面」と「購入明細画面」の仕様を満たすための最小限のテーブルを定義し、結合して取り出します。

なので、まずはそれぞれの画面の必要項目を書き出して、イメージしてみるのが良いと思います。
例えばこんな感じ↓
//====================================//
・購入履歴画面
注文番号		購入日時		合計金額
19208		2020/09/18	¥3,520

・購入明細画面
商品名	商品価格		購入数	小計
商品1	¥120		3		¥360
商品2	¥100		2		¥200
商品3	¥200		5		¥1,000
…
//====================================//

これがイメージできたら、必要項目をザッと書き出します。
そしてそれらを「正規化」します。
正規化がわからなくなったら、教科書をもう一度読んでみましょう！

2020-09-19 07:19 UTC, ryoma1200 commented
ご確認いただきありがとうございます！
ご指摘を踏まえていくつか修正いたしました。

１. 冗長を避けるために、order_numカラムの紐付けで得られるデータは削除しました。
　（historyテーブルのprice_sumカラム、payment_statementテーブルのuser_idカラムとcreate_datetimeカラムを削除しました。）

２. シングルクォート( ' )になっていた箇所をすべてバッククォート( ` )に置換しなおし、クエリ実行時にエラーが出ないようにしました。
　
ご確認のほどよろしくお願いいたします。

2020-09-22 01:14 UTC, kamezaki01 requested changes

2020-09-22 08:37 UTC, ryoma1200 commented
教えていただいた箇所を訂正いたしました。

１. テーブル名をorder、order_itemに変更しました。
２. order_itemテーブルからorder_numのカラムを削除しました。
３. 外部キーの設定を行いました（order_idで）。
（外部キーの設定の仕方にあまり自信がないので、ご確認していただけると幸いです。）

どうぞよろしくお願いいたします。

2020-09-22 10:55 UTC, kamezaki01 commented on lamp_dock/append_schema.sql
> +    ON DELETE RESTRICT ON UPDATE RESTRICT;       -- 参照元を delete or update しようとするとエラーになる
これでもOKですが、サンプルのように"ON DELETE CASCADE"でもOKです。

2020-09-22 10:55 UTC, merged