テーブル課題２　追加テーブルへのデータ保存
ryoma1200/lamp_practice pull request #15
Opened 2020-09-28 06:05 UTC by ryoma1200

orderテーブル、order_itemテーブルへの追加処理を導入しました。
ご確認のほどよろしくお願いいたします。　#14

2020-09-30 04:08 UTC, kamezaki01 requested changes

2020-09-30 04:08 UTC, kamezaki01 commented on www/model/cart.php
> +    delete_user_carts($db, $carts[0]['user_id']);
トランザクションが必要です。

2020-09-30 05:41 UTC, ryoma1200 commented
cart.phpのモデルのpurchase_carts()に、
トランザクション処理を追加しました。 #14

2020-10-02 02:55 UTC, kamezaki01 commented
コンフリクトを起こしているので、解消してください。
よくわからなかったらレッスンでしましょう！

2020-10-02 04:52 UTC, ryoma1200 commented
ご確認いただきありがとうございました。
次回のレッスンで教えていただければと思います！

2020-10-04 11:10 UTC, merged