セキュリティ・脆弱性課題２　
ryoma1200/lamp_practice pull request #9
Opened 2020-09-17 05:44 UTC by ryoma1200

SQLのクエリの生成の過程で、
直接変数の埋め込んでいたものを、
プレースホルダに値をバインドするやり方に変更した。#6

2020-09-21 05:12 UTC, kamezaki01 requested changes

2020-09-21 05:12 UTC, kamezaki01 commented on www/model/user.php
> +  $statement->bindValue(1, $name, PDO::PARAM_INT);
PDO::PARAM_STRですかね？

2020-09-21 05:12 UTC, kamezaki01 commented on www/model/user.php
> +  $statement->bindValue(2, $password, PDO::PARAM_INT);
ここも同様

2020-09-21 05:20 UTC, ryoma1200 commented on www/model/user.php
> +  $statement->bindValue(2, $password, PDO::PARAM_INT);
失礼いたしました。
どちらの$nameも PARAM_STRの間違いでした。

2020-09-22 05:45 UTC, ryoma1200 commented
nameとpasswordを
PDO::PARAM_**INT**→PDO::PARAM_**STR**
に変更いたしました。
ご確認のほどよろしくお願いいたします。

2020-09-22 09:36 UTC, merged